### PR TITLE
Use Python 3

### PR DESCRIPTION
**Pull request by rojiani**
The scripts work with Python 3 now (with a few changes).
Remove Python 2 requirement.

### CODE REVIEW

**Comment by dandoh** [comment]
Me too, was able to generate ligaturized menlo

**Comment by rojiani** [comment]
ping @ToxicFrog - can you take a look when you have some time?

**Comment by rojiani** [comment]
@NanoSpicer @ToxicFrog @vikky49 @karambaq - Approval needed to merge

**Comment by farid-fari** [comment]
Can confirm this works as intended

**Pull request merged**
