### PR TITLE
Bump to Fira v4

### LINKED ISSUE #85: Update for Fira Code V3?
Hello!
[Fira Code V3](https://github.com/tonsky/FiraCode/releases/tag/3) is out, so I'm wondering if there's an update planned for this as well.

### PR DESCRIPTION
**Pull request by H12**
This bumps the Fira Code submodule to the version 4 release tag commit, the hash for which is d42e7276fa925e5f82748f3ec9ea429736611b48.

I ran `make` with all the base fonts and ligatures enabled, and did not see any errors in the output. Not sure whether there's any other testing I should do, but as of now this appears to be a pretty painless bump.

Let me know if anything looks off!

Resolves #85

### CODE REVIEW

**Comment by MrJmpl3** [comment]
Now, Fira Code have v4.

**Comment by H12** [comment]
Thanks @MrJmpl3! I've updated this PR to the Fira v4 release commit.

**Comment by Angalexik** [comment]
This bump breaks all arrow and markdown header ligatures

**Comment by H12** [comment]
Thanks, @Angalexik, that makes sense. Fira v4 now supports arbitrarily-long ligatures, which don't seem compatible with the way this project was built.

After looking into it, I don't think a simple bump would be particularly useful, and I'm not a strong enough Python dev to know how to fill the gaps.

Because of this, I'm closing this PR.

**Pull request closed without merging**
